version: '3.8'

services:
<<<<<<< HEAD
  backend:
    image: ${DOCKER_USERNAME}/final-backend:latest
    container_name: spring-boot-app
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
=======
  core-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: final-backend:latest
    container_name: core-api
    restart: unless-stopped
    environment:
#      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
      - SPRING_PROFILES_ACTIVE=local
>>>>>>> 8bc229d (test)
      - STORAGE_DATABASE_CORE_DB_URL=${STORAGE_DATABASE_CORE_DB_URL}
      - STORAGE_DATABASE_CORE_DB_USERNAME=${STORAGE_DATABASE_CORE_DB_USERNAME}
      - STORAGE_DATABASE_CORE_DB_PASSWORD=${STORAGE_DATABASE_CORE_DB_PASSWORD}
      - JAVA_OPTS=-Xms256m -Xmx512m
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 600M

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
<<<<<<< HEAD
    restart: unless-stopped
    volumes:
      - ./support/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
=======
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - ./support/monitoring/src/main/resources:/etc/prometheus:ro
>>>>>>> 8bc229d (test)
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=7d'
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 300M

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
<<<<<<< HEAD
=======
    ports:
      - "3000:3000"
>>>>>>> 8bc229d (test)
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_SERVER_ROOT_URL=https://${GRAFANA_DOMAIN}
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 200M

<<<<<<< HEAD
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - grafana
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 50M

=======
>>>>>>> 8bc229d (test)
networks:
  app-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: