version: "3.8"

services:
  core-api:
    image: voteland-api
    build:
      context: ../..
      dockerfile: ../../Dockerfile
    container_name: core-api
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
    networks:
      - voteland-net

networks:
  voteland-net:
    external: true